### ISSUE TITLE
Removing threshold (returning more than 1 entry) causes a bug

### ISSUE THREAD

**Issue by itpun** [aptmac/byteboy#12]
Steps:

1) change THRESHOLD in analysis to '0'
2) Run `python byteboy.py ../motivating-example/InfLoop.java`
3) Ctrl C after a few seconds

All previous println statements from analysis.java are removed and this is returned:

`You have not supplied a Java application to Byteboy.
The functionality available to you is Manual Rule Creation.`

**Comment by aptmac** [comment]
I don't know why it goes into that side of the if statement, my console even starts showing the analysis portion. I'll look into that a bit more.

However, I think it may have something to do with the threshold value, because if you comment out lines 52-57 in analysis then the program starts working again

**Comment by aptmac** [comment]
What's weird is that when the THRESHOLD is less than 6, it won't work at all for me. 
If THRESHOLD is between 6 and 8, then it fails the first time and then works on a subsequent run.
If THRESHOLD is greater than 8, it works as normal.

**Comment by itpun** [comment]
Fixed with latest push in master
